name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - 15-create-cicd-pipeline-for-ec2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner machine
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Transfer files to EC2 instance
      - name: Transfer Files to EC2
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -r -i ~/.ssh/id_rsa . ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/Kyoko-Bot

      # Install dependencies and build
      - name: Install Dependencies and Build
        run: |
          pip install -r requirements.txt

      # Transfer files to EC2 instance
      # - name: Transfer Files to EC2
      #   env:
      #     EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      #   run: |
      #     scp -r -i ~/.ssh/id_rsa . ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/Kyoko-Bot