name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - 15-create-cicd-pipeline-for-ec2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner machine
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install dependencies and build
      - name: Install Dependencies and Build
        run: |
          pwd && cd /home/ec2-user/Kyoko-Bot && pip install -r requirements.txt

      # Transfer files to EC2 instance
      - name: Transfer Files to EC2
        run: |
          scp -r -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} . ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/Kyoko-Bot

      # SSH into the EC2 instance and update the repository
      - name: SSH into EC2 and Update Repository
        run: |
          ssh -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'cd /home/ec2-user/Kyoko-Bot && git pull'

