name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - 15-create-cicd-pipeline-for-ec2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner machine
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install dependencies and build
      - name: Install Dependencies and Build
        run: |
          pwd && whoami && cd /home/ec2-user/Kyoko-Bot && pip install -r requirements.txt

      # Transfer files to EC2 instance
      - name: Transfer Files to EC2
        run: |
          cp -r /home/runner/work/Kyoko-Bot/Kyoko-Bot /home/ec2-user/Kyoko-Bot